language: php
dist: trusty
sudo: false

branches:
  only:
    - master
    - trunk

jobs:
  fast_finish: true
  include:
    - php: 7.0
      env: WP_VERSION=4.8 WP_MULTISITE=1 PHPLINT=1 PHPCS=1 CHECKJS=1 COVERAGE=1 TRAVIS_NODE_VERSION=node
    - php: 5.2
      dist: precise
      env: WP_VERSION=4.7 WP_MULTISITE=1 PHPLINT=1
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.6
    - php: 5.6
      env: WP_VERSION=4.6
    - php: 7.1
      env: WP_VERSION=4.8
    - php: 5.2
      dist: precise
      env: WP_VERSION=master
    - php: nightly
      env: WP_VERSION=master
