sudo: false
language: php

#branches:
#  only:
#    - master

env:
  global:
    - WP_VERSION=latest
    - WP_MULTISITE=0
    - TEST_BUILD_DIR=${TRAVIS_BUILD_DIR}
    - INSTALL_PHPUNIT=true
    - DB_HOST=localhost
    - PATH=${HOME}/bin:${PATH}
    - WP_TEST_URL=http://localhost:12000
    - WP_TEST_USER=test
    - WP_TEST_USER_PASS=test
    - WP_PROJECT_TYPE=plugin

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: RUN_CS_FIXER=true
    - php: 7.0
    - php: 7.1
    
  allow_failures:
    - php: nightly

before_script:
  # Install composer packages before trying to activate themes or plugins
  # - composer install
  - git clone https://github.com/Seravo/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

before_install:
  - pushd ${HOME}

script:
  - phpunit
  - cd wp-tests/spec && bundle exec rspec test.rb
